### ISSUE TITLE
Error when loading documentation for @excalidraw/excalidraw

### ISSUE THREAD

**Issue by testersen** [pastelsky/tsdocs#34] opened 2024-01-02 19:20 UTC
```
              Missing symbol when converting import type node at: import("react").FC void) | undefined;
    onDock?: ((docked: boolean) => void) | undefined;
    docked?: boolean | undefined;
    className?: string | undefined;
    __fallback?: boolean | undefined;
}, "name">, "children">, "onDock"> & {
    /** pass `false` to disable docking */
    onDock?: SidebarProps["onDock"] | false;
} & {
    __fallback?: boolean | undefined;
}>
at Object.convert in typedoc/dist/lib/converter/types.js:232
at convertType in typedoc/dist/lib/converter/types.js:82
at  in typedoc/dist/lib/converter/types.js:262
at Array.map in :null
at Object.convert in typedoc/dist/lib/converter/types.js:262
at convertType in typedoc/dist/lib/converter/types.js:82
at _classThis.convertType in typedoc/dist/lib/converter/converter.js:211
at Object.convertVariable in typedoc/dist/lib/converter/symbols.js:487
at convertSymbol in typedoc/dist/lib/converter/symbols.js:126
at Object.convertAlias in typedoc/dist/lib/converter/symbols.js:451
```

**Comment by pastelsky** [comment] 2024-01-03 03:39
Duplicate of https://github.com/pastelsky/tsdocs/issues/34

**Closed by pastelsky** 2024-01-03 03:39 UTC

**Comment by testersen** [comment] 2024-01-03 05:36
@pastelsky This is #34
